import localFont from "next/font/local";

const thunder = localFont({
    src: [
        { path: "./Thunder-BlackHC.woff2", weight: "900", style: "normal" },
        { path: "./Thunder-BlackHCItalic.woff2", weight: "900", style: "italic" },
        { path: "./Thunder-BlackLC.woff2", weight: "900", style: "normal" },
        { path: "./Thunder-BlackLCItalic.woff2", weight: "900", style: "italic" },
        { path: "./Thunder-BoldHC.woff2", weight: "700", style: "normal" },
        { path: "./Thunder-BoldHCItalic.woff2", weight: "700", style: "italic" },
        { path: "./Thunder-BoldLC.woff2", weight: "700", style: "normal" },
        { path: "./Thunder-BoldLCItalic.woff2", weight: "700", style: "italic" },
        { path: "./Thunder-ExtraBoldHC.woff2", weight: "800", style: "normal" },
        { path: "./Thunder-ExtraBoldHCItalic.woff2", weight: "800", style: "italic" },
        { path: "./Thunder-ExtraBoldLC.woff2", weight: "800", style: "normal" },
        { path: "./Thunder-ExtraBoldLCItalic.woff2", weight: "800", style: "italic" },
        { path: "./Thunder-ExtraLightHC.woff2", weight: "200", style: "normal" },
        { path: "./Thunder-ExtraLightHCItalic.woff2", weight: "200", style: "italic" },
        { path: "./Thunder-ExtraLightLC.woff2", weight: "200", style: "normal" },
        { path: "./Thunder-ExtraLightLCItalic.woff2", weight: "200", style: "italic" },
        { path: "./Thunder-HC.woff2", weight: "400", style: "normal" },
        { path: "./Thunder-HCItalic.woff2", weight: "400", style: "italic" },
        { path: "./Thunder-LC.woff2", weight: "400", style: "normal" },
        { path: "./Thunder-LCItalic.woff2", weight: "400", style: "italic" },
        { path: "./Thunder-LightHC.woff2", weight: "300", style: "normal" },
        { path: "./Thunder-LightHCItalic.woff2", weight: "300", style: "italic" },
        { path: "./Thunder-LightLC.woff2", weight: "300", style: "normal" },
        { path: "./Thunder-LightLCItalic.woff2", weight: "300", style: "italic" },
        { path: "./Thunder-MediumHC.woff2", weight: "500", style: "normal" },
        { path: "./Thunder-MediumHCItalic.woff2", weight: "500", style: "italic" },
        { path: "./Thunder-MediumLC.woff2", weight: "500", style: "normal" },
        { path: "./Thunder-MediumLCItalic.woff2", weight: "500", style: "italic" },
        { path: "./Thunder-SemiBoldHC.woff2", weight: "600", style: "normal" },
        { path: "./Thunder-SemiBoldHCItalic.woff2", weight: "600", style: "italic" },
        { path: "./Thunder-SemiBoldLC.woff2", weight: "600", style: "normal" },
        { path: "./Thunder-SemiBoldLCItalic.woff2", weight: "600", style: "italic" },
        { path: "./Thunder-ThinHC.woff2", weight: "100", style: "normal" },
        { path: "./Thunder-ThinHCItalic.woff2", weight: "100", style: "italic" },
        { path: "./Thunder-ThinLC.woff2", weight: "100", style: "normal" },
        { path: "./Thunder-ThinLCItalic.woff2", weight: "100", style: "italic" },
    ],
});

export default thunder;